name: Master Branch Protection

on:
  pull_request:
    branches: [ "master" ]

jobs:
  master-branch-protection:
    name: Master Branch Protection
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from dev branch
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Error: Pull requests to master branch must come from dev branch"
            exit 1
          fi